# Generated by Django 6.0.6 on 2026-06-18 07:54

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市')),
                ('baby_stage', models.CharField(blank=True, max_length=32, null=True, verbose_name='宝宝阶段')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('bio', models.CharField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('show_real_name', models.BooleanField(default=False, verbose_name='是否显示真名')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='是否已解锁')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='解锁时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='love_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交友资料',
                'verbose_name_plural': '交友资料',
                'db_table': 'social_love_profile',
            },
        ),
        migrations.CreateModel(
            name='SisterTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('name', models.CharField(max_length=64, verbose_name='小队名称')),
                ('goal', models.CharField(choices=[('emotion', '情绪管理'), ('parent_child_english', '亲自英语'), ('self_growth', '自我成长'), ('persistence', '坚持打卡')], max_length=32, verbose_name='目标')),
                ('max_members', models.IntegerField(default=5, verbose_name='最大成员数')),
                ('invite_code', models.CharField(max_length=16, unique=True, verbose_name='邀请码')),
                ('team_consecutive_days', models.IntegerField(default=0, verbose_name='小队连续打卡天数')),
                ('growth_value', models.IntegerField(default=0, verbose_name='成长值')),
                ('status', models.CharField(choices=[('active', '活跃'), ('disbanded', '已解散')], default='active', max_length=16, verbose_name='状态')),
                ('disbanded_at', models.DateTimeField(blank=True, null=True, verbose_name='解散时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '姐妹小队',
                'verbose_name_plural': '姐妹小队',
                'db_table': 'social_sister_team',
            },
        ),
        migrations.CreateModel(
            name='SisterTeamActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_date', models.DateField(verbose_name='业务日期')),
                ('type', models.CharField(choices=[('checkin', '已打卡'), ('pending', '待打卡')], max_length=16, verbose_name='类型')),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='内容')),
                ('hug_count', models.IntegerField(default=0, verbose_name='拥抱数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='social.sisterteam', verbose_name='小队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_activities', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '小队动态',
                'verbose_name_plural': '小队动态',
                'db_table': 'social_sister_team_activity',
                'unique_together': {('team', 'user', 'biz_date')},
            },
        ),
        migrations.CreateModel(
            name='SisterTeamEncouragement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encouragements', to='social.sisterteamactivity', verbose_name='动态')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_encouragements', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_encouragements', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '小队鼓励',
                'verbose_name_plural': '小队鼓励',
                'db_table': 'social_sister_team_encouragement',
            },
        ),
        migrations.CreateModel(
            name='SquarePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('text', models.CharField(max_length=500, verbose_name='内容')),
                ('tag', models.CharField(blank=True, max_length=32, null=True, verbose_name='标签')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('audit_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='approved', max_length=16, verbose_name='审核状态')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_posts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '广场帖子',
                'verbose_name_plural': '广场帖子',
                'db_table': 'social_square_post',
            },
        ),
        migrations.CreateModel(
            name='SquarePostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.squarepostcomment', verbose_name='父评论')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.squarepost', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '帖子评论',
                'verbose_name_plural': '帖子评论',
                'db_table': 'social_square_post_comment',
            },
        ),
        migrations.CreateModel(
            name='SquarePostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, verbose_name='图片URL')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.squarepost', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '帖子图片',
                'verbose_name_plural': '帖子图片',
                'db_table': 'social_square_post_image',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='LoveFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_following', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_followers', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
            options={
                'verbose_name': '交友关注',
                'verbose_name_plural': '交友关注',
                'db_table': 'social_love_follow',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='SisterTeamInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hug', '拥抱'), ('like', '点赞'), ('remind', '提醒')], max_length=16, verbose_name='动作')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='social.sisterteamactivity', verbose_name='动态')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interactions', to=settings.AUTH_USER_MODEL, verbose_name='发起者')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '小队互动',
                'verbose_name_plural': '小队互动',
                'db_table': 'social_sister_team_interaction',
                'unique_together': {('activity', 'from_user', 'action')},
            },
        ),
        migrations.CreateModel(
            name='SisterTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '队长'), ('member', '队员')], default='member', max_length=16, verbose_name='角色')),
                ('joined_at', models.DateTimeField(default=common.utils.now_cst, verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('total_checkin_days', models.IntegerField(default=0, verbose_name='累计打卡天数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social.sisterteam', verbose_name='小队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '小队成员',
                'verbose_name_plural': '小队成员',
                'db_table': 'social_sister_team_member',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_team_per_user')],
            },
        ),
        migrations.CreateModel(
            name='SisterTeamRemindLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_date', models.DateField(verbose_name='业务日期')),
                ('channel', models.CharField(choices=[('system_msg', '系统消息'), ('push', '推送')], max_length=16, verbose_name='渠道')),
                ('sent_at', models.DateTimeField(default=common.utils.now_cst, verbose_name='发送时间')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminds', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remind_logs', to='social.sisterteam', verbose_name='小队')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reminds', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '提醒日志',
                'verbose_name_plural': '提醒日志',
                'db_table': 'social_sister_team_remind_log',
                'constraints': [models.UniqueConstraint(fields=('team', 'from_user', 'to_user', 'biz_date'), name='unique_remind_per_day')],
            },
        ),
        migrations.CreateModel(
            name='SquarePostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.squarepost', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '帖子点赞',
                'verbose_name_plural': '帖子点赞',
                'db_table': 'social_square_post_like',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
