# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(db_index=True, default='', max_length=32, unique=True, verbose_name='业务主键')),
                ('openid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='微信openid')),
                ('unionid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信unionid')),
                ('nickname', models.CharField(default='', max_length=64, verbose_name='昵称')),
                ('avatar_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='头像URL')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号(加密)')),
                ('phone_masked', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号(脱敏)')),
                ('gender', models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('admin', '管理员'), ('editor', '编辑'), ('reviewer', '审核员')], default='user', max_length=32, verbose_name='角色')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否管理员')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='是否禁用')),
                ('disabled_reason', models.CharField(blank=True, max_length=256, null=True, verbose_name='禁用原因')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='禁用时间')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'core_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码哈希')),
                ('refresh_token_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='刷新Token哈希')),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='刷新Token过期时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('last_login_user_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='最后登录UA')),
                ('failed_login_count', models.IntegerField(default=0, verbose_name='连续登录失败次数')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户认证',
                'verbose_name_plural': '用户认证',
                'db_table': 'core_user_auth',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('baby_stage', models.CharField(blank=True, choices=[('kindergarten', '幼儿园'), ('lower', '小学低年级'), ('upper', '小学高年级'), ('junior', '初中')], max_length=32, null=True, verbose_name='宝宝阶段')),
                ('region', models.CharField(blank=True, max_length=64, null=True, verbose_name='地区')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市')),
                ('bio', models.CharField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('plan_status', models.CharField(choices=[('none', '未加入'), ('trial7', '7天试用'), ('trial21', '21天试用'), ('21d_plan', '21天计划'), ('100d_plan', '100天计划'), ('year365', '365天年卡')], default='none', max_length=16, verbose_name='计划状态')),
                ('plan_started_at', models.DateTimeField(blank=True, null=True, verbose_name='计划开始时间')),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='计划过期时间')),
                ('trial21_unlocked', models.BooleanField(default=False, verbose_name='是否解锁21天试用')),
                ('invite_progress', models.IntegerField(default=0, verbose_name='邀请进度')),
                ('checked_days', models.IntegerField(default=0, verbose_name='已打卡天数')),
                ('missed_days', models.IntegerField(default=0, verbose_name='缺卡天数')),
                ('consecutive_days', models.IntegerField(default=0, verbose_name='连续打卡天数')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='最长连续天数')),
                ('course_unlocked', models.IntegerField(default=0, verbose_name='已解锁课程数')),
                ('course_total', models.IntegerField(default=0, verbose_name='课程总数')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'core_user_profile',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('wechat_mp', '微信小程序'), ('wechat_subscribe', '微信订阅消息')], max_length=32, verbose_name='推送渠道')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('device_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('last_active_at', models.DateTimeField(verbose_name='最后活跃时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '推送Token',
                'verbose_name_plural': '推送Token',
                'db_table': 'core_push_token',
                'indexes': [models.Index(fields=['user', 'provider'], name='idx_push_user_provider')],
            },
        ),
    ]
