# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KidAssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='模板编码')),
                ('name', models.CharField(max_length=64, verbose_name='模板名称')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测评模板',
                'verbose_name_plural': '测评模板',
                'db_table': 'kid_assessment_template',
            },
        ),
        migrations.CreateModel(
            name='KidAssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('score_total', models.IntegerField(blank=True, null=True, verbose_name='总分')),
                ('result_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='结果标题')),
                ('result_copy', models.TextField(blank=True, null=True, verbose_name='结果文案')),
                ('action_list', models.JSONField(default=list, verbose_name='行动建议')),
                ('matched_policy_ids', models.JSONField(default=list, verbose_name='匹配政策ID列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kid_assessment.kidassessmenttemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '测评提交',
                'verbose_name_plural': '测评提交',
                'db_table': 'kid_assessment_submission',
            },
        ),
        migrations.CreateModel(
            name='KidAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='题目标识')),
                ('type', models.CharField(choices=[('single', '单选'), ('multi', '多选'), ('text', '文本'), ('number', '数字')], max_length=16, verbose_name='题目类型')),
                ('title', models.CharField(max_length=255, verbose_name='题目标题')),
                ('options', models.JSONField(default=list, verbose_name='选项')),
                ('step', models.IntegerField(verbose_name='步骤')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('score_rules', models.JSONField(default=dict, verbose_name='评分规则')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kid_assessment.kidassessmenttemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '测评题目',
                'verbose_name_plural': '测评题目',
                'db_table': 'kid_assessment_question',
                'unique_together': {('template', 'key')},
            },
        ),
        migrations.CreateModel(
            name='KidChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('has_done_assessment', models.BooleanField(default=False, verbose_name='是否已完成测评')),
                ('grade_group', models.CharField(blank=True, max_length=16, null=True, verbose_name='年级组')),
                ('grade_option', models.CharField(blank=True, max_length=16, null=True, verbose_name='年级选项')),
                ('english_level', models.CharField(blank=True, max_length=4, null=True, verbose_name='英语水平')),
                ('core_insight', models.JSONField(default=list, verbose_name='核心洞察')),
                ('recommended_plan', models.CharField(blank=True, max_length=16, null=True, verbose_name='推荐方案')),
                ('answers_snapshot', models.JSONField(default=dict, verbose_name='答案快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('latest_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_profiles', to='kid_assessment.kidassessmentsubmission', verbose_name='最新测评')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '宝宝档案',
                'verbose_name_plural': '宝宝档案',
                'db_table': 'kid_child_profile',
            },
        ),
        migrations.CreateModel(
            name='KidAssessmentScoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='得分项标识')),
                ('name', models.CharField(max_length=64, verbose_name='得分项名称')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_items', to='kid_assessment.kidassessmentsubmission', verbose_name='提交记录')),
            ],
            options={
                'verbose_name': '测评得分项',
                'verbose_name_plural': '测评得分项',
                'db_table': 'kid_assessment_score_item',
                'unique_together': {('submission', 'key')},
            },
        ),
        migrations.CreateModel(
            name='KidAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='文本答案')),
                ('answer_options', models.JSONField(default=list, verbose_name='选项答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kid_assessment.kidassessmentquestion', verbose_name='题目')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kid_assessment.kidassessmentsubmission', verbose_name='提交记录')),
            ],
            options={
                'verbose_name': '测评答案',
                'verbose_name_plural': '测评答案',
                'db_table': 'kid_assessment_answer',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
