# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('milestone', '里程碑')], default='daily', max_length=32, verbose_name='分类')),
                ('question', models.CharField(max_length=500, verbose_name='问题')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '反思问题',
                'verbose_name_plural': '反思问题',
                'db_table': 'checkin_reflection_question',
            },
        ),
        migrations.CreateModel(
            name='DailyLesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(db_index=True, help_text='1-365', unique=True, verbose_name='第N天')),
                ('theme', models.CharField(max_length=255, verbose_name='主题')),
                ('task', models.CharField(max_length=500, verbose_name='当日任务')),
                ('cover_image', models.CharField(blank=True, max_length=512, null=True, verbose_name='封面图')),
                ('audio_src', models.CharField(blank=True, max_length=512, null=True, verbose_name='音频URL')),
                ('audio_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='音频标题')),
                ('audio_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='音频副标题')),
                ('audio_duration', models.CharField(blank=True, max_length=16, null=True, verbose_name='音频时长')),
                ('quote', models.CharField(max_length=255, verbose_name='金句')),
                ('meaning', models.CharField(blank=True, max_length=500, null=True, verbose_name='金句释义')),
                ('copy', models.TextField(verbose_name='当日文案')),
                ('pronunciation', models.JSONField(blank=True, default=list, verbose_name='发音拆解')),
                ('speaking_examples', models.JSONField(blank=True, default=list, verbose_name='口语例句')),
                ('definition_notes', models.JSONField(blank=True, default=list, verbose_name='表达理解')),
                ('takeaways', models.JSONField(blank=True, default=list, verbose_name='短语提炼')),
                ('translation_practice', models.JSONField(blank=True, default=list, verbose_name='翻译练习')),
                ('encouragement', models.CharField(blank=True, max_length=500, null=True, verbose_name='鼓励语')),
                ('version', models.IntegerField(default=1, verbose_name='课程版本')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '每日课程',
                'verbose_name_plural': '每日课程',
                'db_table': 'checkin_daily_lesson',
                'ordering': ['day'],
                'indexes': [models.Index(condition=models.Q(('is_published', True)), fields=['is_published'], name='idx_daily_lesson_published')],
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biz_date', models.DateField(db_index=True, verbose_name='自然日')),
                ('main_checkin_completed', models.BooleanField(default=False, verbose_name='主打卡完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('reflection', models.TextField(blank=True, null=True, verbose_name='反思内容')),
                ('audio_played_seconds', models.IntegerField(default=0, verbose_name='音频播放秒数')),
                ('cashback_earned', models.BigIntegerField(default=0, verbose_name='当日返现（分）')),
                ('is_missed', models.BooleanField(default=False, verbose_name='是否漏打卡')),
                ('client_meta', models.JSONField(blank=True, default=dict, verbose_name='客户端元信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='checkin.dailylesson', verbose_name='关联课程')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'db_table': 'checkin_checkin',
            },
        ),
        migrations.CreateModel(
            name='AudioPlayLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biz_date', models.DateField(verbose_name='自然日')),
                ('play_seconds', models.IntegerField(verbose_name='播放秒数')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='播放时间')),
                ('client_meta', models.JSONField(blank=True, default=dict, verbose_name='客户端元信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_play_logs', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.dailylesson')),
            ],
            options={
                'verbose_name': '音频播放日志',
                'verbose_name_plural': '音频播放日志',
                'db_table': 'checkin_audio_play_log',
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('source', models.CharField(choices=[('daily', '每日任务'), ('policy_impact', '政策影响')], default='daily', max_length=32, verbose_name='来源')),
                ('source_policy_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联政策ID')),
                ('title', models.CharField(max_length=255, verbose_name='任务标题')),
                ('category', models.CharField(blank=True, max_length=64, null=True, verbose_name='分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('frequency', models.CharField(blank=True, max_length=64, null=True, verbose_name='频率')),
                ('estimated_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='预计耗时')),
                ('grade_range', models.JSONField(blank=True, default=list, verbose_name='适用年级')),
                ('ability_tags', models.JSONField(blank=True, default=list, verbose_name='能力标签')),
                ('is_template', models.BooleanField(default=True, verbose_name='是否模板')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '子任务',
                'verbose_name_plural': '子任务',
                'db_table': 'checkin_sub_task',
                'indexes': [models.Index(fields=['source', 'source_policy_id'], name='idx_sub_task_source_policy'), models.Index(fields=['category'], name='idx_sub_task_category')],
            },
        ),
        migrations.CreateModel(
            name='CheckinSubTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户留言')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='checkin.checkin')),
                ('sub_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.subtask')),
            ],
            options={
                'verbose_name': '打卡子任务',
                'verbose_name_plural': '打卡子任务',
                'db_table': 'checkin_checkin_sub_task',
            },
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', '-completed_at'], name='idx_checkin_user_completed_at'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['-biz_date'], name='idx_checkin_biz_date'),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('user', 'biz_date')},
        ),
        migrations.AddIndex(
            model_name='audioplaylog',
            index=models.Index(fields=['user', 'biz_date'], name='idx_audio_play_user_date'),
        ),
        migrations.AlterUniqueTogether(
            name='checkinsubtask',
            unique_together={('checkin', 'sub_task')},
        ),
    ]
