# Generated by Django 6.0.6 on 2026-06-18 07:54

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(unique=True, verbose_name='月份')),
                ('badge_level', models.IntegerField(verbose_name='徽章等级')),
                ('label', models.CharField(max_length=64, verbose_name='标签')),
                ('copy', models.TextField(verbose_name='文案')),
                ('required_days', models.IntegerField(verbose_name='所需天数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '里程碑定义',
                'verbose_name_plural': '里程碑定义',
                'db_table': 'mom_growth_milestone_definition',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='OfflineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='活动标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活动描述')),
                ('city', models.CharField(max_length=64, verbose_name='城市')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='地点')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('end_at', models.DateTimeField(verbose_name='结束时间')),
                ('max_seats', models.IntegerField(verbose_name='最大名额')),
                ('taken_seats', models.IntegerField(default=0, verbose_name='已占名额')),
                ('cover', models.CharField(blank=True, max_length=512, null=True, verbose_name='封面图')),
                ('status', models.CharField(choices=[('open', '报名中'), ('closed', '已截止'), ('cancelled', '已取消')], default='open', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '线下活动',
                'verbose_name_plural': '线下活动',
                'db_table': 'mom_growth_offline_activity',
            },
        ),
        migrations.CreateModel(
            name='OfflineActivitySignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('signed', '已报名'), ('cancelled', '已取消'), ('attended', '已参加')], default='signed', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='mom_growth.offlineactivity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_signups', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'db_table': 'mom_growth_offline_activity_signup',
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=common.utils.now_cst, verbose_name='解锁时间')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_records', to='mom_growth.milestonedefinition', verbose_name='里程碑')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户里程碑',
                'verbose_name_plural': '用户里程碑',
                'db_table': 'mom_growth_user_milestone',
                'unique_together': {('user', 'milestone')},
            },
        ),
    ]
