# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='邀请码')),
                ('type', models.CharField(choices=[('sister_team', '姐妹团'), ('plan_trial21', '21天试用'), ('general', '通用')], default='general', max_length=16, verbose_name='邀请码类型')),
                ('ref_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='关联ID')),
                ('use_limit', models.IntegerField(default=0, help_text='0=无限制', verbose_name='使用次数限制')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_codes', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '邀请码',
                'verbose_name_plural': '邀请码',
                'db_table': 'invite_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待注册'), ('registered', '已注册'), ('first_checkin', '首次打卡'), ('confirmed', '已确认'), ('expired', '已过期')], default='pending', max_length=16, verbose_name='邀请状态')),
                ('first_checkin_at', models.DateTimeField(blank=True, null=True, verbose_name='首次打卡时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('invite_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='invite.invitecode', verbose_name='邀请码')),
                ('invitee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_received', to=settings.AUTH_USER_MODEL, verbose_name='被邀请人')),
                ('inviter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_sent', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
            ],
            options={
                'verbose_name': '邀请记录',
                'verbose_name_plural': '邀请记录',
                'db_table': 'invite_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
