# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='计划代码')),
                ('name', models.CharField(max_length=64, verbose_name='计划名称')),
                ('price_cents', models.BigIntegerField(verbose_name='价格（分）')),
                ('duration_days', models.IntegerField(verbose_name='时长（天）')),
                ('cashback_per_day', models.IntegerField(default=0, verbose_name='每日返现（分）')),
                ('course_reward_value_cents', models.BigIntegerField(default=0, verbose_name='满勤课程价值（分）')),
                ('max_badges', models.IntegerField(default=0, verbose_name='最大勋章数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '计划SKU',
                'verbose_name_plural': '计划SKU',
                'db_table': 'finance_plan',
            },
        ),
        migrations.CreateModel(
            name='CashbackAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance_cents', models.BigIntegerField(default=0, verbose_name='当前余额（分）')),
                ('frozen_cents', models.BigIntegerField(default=0, verbose_name='冻结金额（分）')),
                ('total_earned_cents', models.BigIntegerField(default=0, verbose_name='累计赚取（分）')),
                ('total_withdrawn_cents', models.BigIntegerField(default=0, verbose_name='累计提现（分）')),
                ('expected_cashback_cents', models.BigIntegerField(default=0, verbose_name='应得返现（分）')),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '返现账户',
                'verbose_name_plural': '返现账户',
                'db_table': 'finance_cashback_account',
            },
        ),
        migrations.CreateModel(
            name='CashbackRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('amount_cents', models.BigIntegerField(help_text='正为增加，负为扣减', verbose_name='金额（分）')),
                ('type', models.CharField(choices=[('earn', '赚取'), ('manual_adjust', '手工调整')], max_length=32, verbose_name='类型')),
                ('source', models.CharField(choices=[('daily_checkin', '每日打卡'), ('invite_reward', '邀请奖励'), ('manual', '手工调整')], max_length=32, verbose_name='来源')),
                ('ref_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='关联业务ID')),
                ('biz_date', models.DateField(verbose_name='业务日期')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('operator_id', models.BigIntegerField(blank=True, null=True, verbose_name='操作员ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '返现流水',
                'verbose_name_plural': '返现流水',
                'db_table': 'finance_cashback_record',
                'indexes': [models.Index(fields=['user', '-biz_date'], name='idx_cashback_record_user_date'), models.Index(fields=['type', '-created_at'], name='idx_cashback_record_type')],
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', '生效中'), ('expired', '已过期'), ('cancelled', '已取消')], default='active', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('expires_at', models.DateTimeField(verbose_name='到期时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户计划',
                'verbose_name_plural': '用户计划',
                'db_table': 'finance_user_plan',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_user_plan_user_status'), models.Index(condition=models.Q(('status', 'active')), fields=['expires_at'], name='idx_user_plan_expires_at')],
            },
        ),
    ]
