# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(db_index=True, default='', max_length=32, unique=True, verbose_name='业务主键')),
                ('type', models.CharField(choices=[('system', '系统消息'), ('checkin_remind', '打卡提醒'), ('team', '小队消息'), ('policy', '政策消息')], default='system', max_length=32, verbose_name='消息类型')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='链接')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'message_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('is_pushed', models.BooleanField(default=False, verbose_name='是否已推送')),
                ('pushed_at', models.DateTimeField(blank=True, null=True, verbose_name='推送时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='message.message', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receipts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息回执',
                'verbose_name_plural': '消息回执',
                'db_table': 'message_receipt',
                'unique_together': {('message', 'user')},
            },
        ),
    ]
