# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('name', models.CharField(max_length=64, verbose_name='徽章名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('required_days', models.IntegerField(verbose_name='达成所需天数')),
                ('level', models.IntegerField(default=1, verbose_name='等级（1初心/2坚持/3点亮/4节奏）')),
                ('icon', models.CharField(blank=True, max_length=512, null=True, verbose_name='图标URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '徽章定义',
                'verbose_name_plural': '徽章定义',
                'db_table': 'incentive_badge',
                'ordering': ['level', 'required_days'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('title', models.CharField(max_length=255, verbose_name='课程标题')),
                ('cover', models.CharField(blank=True, max_length=512, null=True, verbose_name='封面图')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('value_cents', models.BigIntegerField(default=0, verbose_name='价值（分）')),
                ('required_cashback_days', models.IntegerField(default=0, verbose_name='兑换所需返现天数')),
                ('redeem_limit_per_user', models.IntegerField(default=1, verbose_name='每人限兑')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'incentive_course',
            },
        ),
        migrations.CreateModel(
            name='CourseExchange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('success', '兑换成功'), ('failed', '兑换失败')], default='pending', max_length=16, verbose_name='状态')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incentive.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '课程兑换',
                'verbose_name_plural': '课程兑换',
                'db_table': 'incentive_course_exchange',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseInquiry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(default='', max_length=32, unique=True, verbose_name='业务ID')),
                ('from_page', models.CharField(default='pages/courses/index', max_length=128, verbose_name='来源页面')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号（加密）')),
                ('phone_masked', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号（脱敏）')),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='手机号SHA256')),
                ('wechat', models.CharField(blank=True, max_length=128, null=True, verbose_name='微信号')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='咨询意向')),
                ('status', models.CharField(choices=[('received', '已收到'), ('contacted', '已联系'), ('converted', '已转化'), ('closed', '已关闭')], default='received', max_length=16, verbose_name='状态')),
                ('follow_up_channel', models.CharField(default='wechat_enterprise', max_length=32, verbose_name='触达渠道')),
                ('operator_id', models.BigIntegerField(blank=True, null=True, verbose_name='跟进人ID')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='首次联系时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('client_meta', models.JSONField(blank=True, default=dict, verbose_name='客户端元信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incentive.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '课程咨询',
                'verbose_name_plural': '课程咨询',
                'db_table': 'incentive_course_inquiry',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_course_inquiry_user'), models.Index(fields=['course', '-created_at'], name='idx_course_inquiry_course'), models.Index(fields=['status', '-created_at'], name='idx_course_inquiry_status')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='解锁上下文')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incentive.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户徽章',
                'verbose_name_plural': '用户徽章',
                'db_table': 'incentive_user_badge',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
