# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('module', models.CharField(choices=[('policy', '政策'), ('user', '用户'), ('order', '订单')], max_length=32, verbose_name='所属模块')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'admin_panel_permission',
            },
        ),
        migrations.CreateModel(
            name='AdminRoleDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='角色代码')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'admin_panel_role',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='用户名')),
                ('password_hash', models.CharField(max_length=255, verbose_name='密码哈希')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('role_code', models.CharField(default='cs', max_length=32, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最近登录IP')),
                ('failed_login_count', models.IntegerField(default=0, verbose_name='失败登录次数')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '管理员账号',
                'verbose_name_plural': '管理员账号',
                'db_table': 'admin_panel_admin_user',
            },
        ),
        migrations.CreateModel(
            name='DataDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=32, verbose_name='字典类型')),
                ('code', models.CharField(max_length=64, verbose_name='代码')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'db_table': 'admin_panel_data_dictionary',
                'unique_together': {('type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AdminRolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.adminpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='admin_panel.adminroledefinition')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'db_table': 'admin_panel_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64, verbose_name='操作')),
                ('target_type', models.CharField(max_length=32, verbose_name='目标类型')),
                ('target_id', models.CharField(max_length=64, verbose_name='目标ID')),
                ('payload_before', models.JSONField(blank=True, null=True, verbose_name='变更前')),
                ('payload_after', models.JSONField(blank=True, null=True, verbose_name='变更后')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='UA')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=16, verbose_name='结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='admin_panel.adminuser')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'admin_panel_audit_log',
                'indexes': [models.Index(fields=['operator', '-created_at'], name='idx_audit_operator_time'), models.Index(fields=['target_type', 'target_id', '-created_at'], name='idx_audit_target')],
            },
        ),
    ]
