# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('daily', '每日海报'), ('sister_invite', '姐妹邀请海报')], max_length=32, verbose_name='海报类型')),
                ('template', models.CharField(blank=True, max_length=64, null=True, verbose_name='模板标识')),
                ('payload', models.JSONField(verbose_name='生成参数')),
                ('poster_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='海报图片URL')),
                ('qrcode_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='二维码URL')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '海报',
                'verbose_name_plural': '海报',
                'db_table': 'media_poster',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=255, unique=True, verbose_name='对象键')),
                ('cdn_url', models.CharField(max_length=512, verbose_name='CDN地址')),
                ('scene', models.CharField(choices=[('avatar', '头像'), ('post_image', '帖子图片'), ('poster_image', '海报图片'), ('policy_image', '政策图片')], max_length=32, verbose_name='场景')),
                ('content_type', models.CharField(max_length=64, verbose_name='文件类型')),
                ('size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '已上传文件',
                'verbose_name_plural': '已上传文件',
                'db_table': 'media_uploaded_file',
                'ordering': ['-created_at'],
            },
        ),
    ]
