# Generated by Django 6.0.6 on 2026-06-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(db_index=True, default='', max_length=32, unique=True, verbose_name='业务主键')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('source_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='来源名称')),
                ('source_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='来源链接')),
                ('policy_summary', models.TextField(blank=True, null=True, verbose_name='政策摘要')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('region', models.CharField(blank=True, max_length=64, null=True, verbose_name='地区')),
                ('stage', models.CharField(blank=True, max_length=64, null=True, verbose_name='阶段')),
                ('grade_range', models.JSONField(blank=True, default=list, verbose_name='年级范围')),
                ('domains', models.JSONField(blank=True, default=list, verbose_name='领域')),
                ('influence_abilities', models.JSONField(blank=True, default=list, verbose_name='影响能力')),
                ('parent_action_suggestions', models.JSONField(blank=True, default=list, verbose_name='家长行动建议')),
                ('front_display_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='前端展示标题')),
                ('front_display_summary', models.TextField(blank=True, null=True, verbose_name='前端展示摘要')),
                ('impact_explanation', models.TextField(blank=True, null=True, verbose_name='影响说明')),
                ('monthly_suggestions', models.JSONField(blank=True, default=list, verbose_name='月度建议')),
                ('weekly_task_suggestions', models.JSONField(blank=True, default=list, verbose_name='每周任务建议')),
                ('focus_directions', models.JSONField(blank=True, default=list, verbose_name='重点方向')),
                ('child_impact_analysis', models.TextField(blank=True, null=True, verbose_name='对孩子的影响分析')),
                ('content_status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('published', '已发布'), ('offline', '已下线'), ('archived', '已归档')], default='draft', max_length=16, verbose_name='内容状态')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('created_by', models.CharField(max_length=64, verbose_name='编辑者标识')),
                ('reviewed_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='审核者标识')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='审核意见')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('published_at_system', models.DateTimeField(blank=True, null=True, verbose_name='系统发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '政策',
                'verbose_name_plural': '政策',
                'db_table': 'policy_policy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAiGenerationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('source_text_hash', models.CharField(max_length=64, verbose_name='源文本哈希')),
                ('source_text_length', models.IntegerField(verbose_name='源文本长度')),
                ('preset_tags', models.JSONField(verbose_name='预设标签')),
                ('output', models.JSONField(verbose_name='输出结果')),
                ('tokens_input', models.IntegerField(blank=True, null=True, verbose_name='输入Token数')),
                ('tokens_output', models.IntegerField(blank=True, null=True, verbose_name='输出Token数')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)')),
                ('error', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI生成日志',
                'verbose_name_plural': 'AI生成日志',
                'db_table': 'policy_ai_generation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='业务主键')),
                ('type', models.CharField(choices=[('region', '地区'), ('stage', '阶段'), ('grade', '年级'), ('domain', '领域'), ('ability', '能力'), ('task', '任务'), ('user_profile', '用户画像')], max_length=32, verbose_name='标签类型')),
                ('name', models.CharField(max_length=64, verbose_name='标签名称')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签值')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '政策标签',
                'verbose_name_plural': '政策标签',
                'db_table': 'policy_tag',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(db_index=True, default='', max_length=32, unique=True, verbose_name='业务主键')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('reviewer', models.CharField(blank=True, max_length=64, null=True, verbose_name='审核者')),
                ('action', models.CharField(choices=[('submit', '提交审核'), ('approve', '通过'), ('reject', '驳回'), ('request_changes', '要求修改')], max_length=16, verbose_name='审核动作')),
                ('comment', models.TextField(verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='policy_app.policy', verbose_name='政策')),
            ],
            options={
                'verbose_name': '政策审核记录',
                'verbose_name_plural': '政策审核记录',
                'db_table': 'policy_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField(db_index=True, default='', max_length=32, unique=True, verbose_name='业务主键')),
                ('title', models.CharField(max_length=255, verbose_name='任务标题')),
                ('category', models.CharField(blank=True, max_length=64, null=True, verbose_name='任务分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('frequency', models.CharField(blank=True, max_length=64, null=True, verbose_name='频率')),
                ('estimated_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='预计耗时')),
                ('grade_range', models.JSONField(blank=True, default=list, verbose_name='适用年级')),
                ('ability_tags', models.JSONField(blank=True, default=list, verbose_name='能力标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='policy_app.policy', verbose_name='政策')),
            ],
            options={
                'verbose_name': '政策任务',
                'verbose_name_plural': '政策任务',
                'db_table': 'policy_task',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyWeeklyTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='任务标题')),
                ('category', models.CharField(blank=True, max_length=64, null=True, verbose_name='任务分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('frequency', models.CharField(blank=True, max_length=64, null=True, verbose_name='频率')),
                ('estimated_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='预计耗时')),
                ('grade_range', models.JSONField(blank=True, default=list, verbose_name='适用年级')),
                ('ability_tags', models.JSONField(blank=True, default=list, verbose_name='能力标签')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to='policy_app.policy', verbose_name='政策')),
            ],
            options={
                'verbose_name': '政策每周任务',
                'verbose_name_plural': '政策每周任务',
                'db_table': 'policy_weekly_task',
                'ordering': ['sort', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyTagRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='policy_app.policy', verbose_name='政策')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_relations', to='policy_app.policytag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '政策标签关联',
                'verbose_name_plural': '政策标签关联',
                'db_table': 'policy_tag_relation',
                'unique_together': {('policy', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('snapshot', models.JSONField(verbose_name='快照数据')),
                ('change_summary', models.CharField(blank=True, max_length=500, null=True, verbose_name='变更说明')),
                ('editor', models.CharField(max_length=64, verbose_name='编辑者')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policy_app.policy', verbose_name='政策')),
            ],
            options={
                'verbose_name': '政策版本',
                'verbose_name_plural': '政策版本',
                'db_table': 'policy_version',
                'ordering': ['-version'],
                'unique_together': {('policy', 'version')},
            },
        ),
    ]
